### ISSUE TITLE
Email: send on Host Europe fails

### ISSUE THREAD

**Issue by svnt** [getkirby/toolkit#107]
sending on "Host Europe" fails.
i have found this info:

http://blog.markusheisterberg.de/webdesign/phpmailer-und-host-europe/

hacked the core at [line 138 in lib/email.php](https://github.com/getkirby/toolkit/blob/master/lib/email.php#L138): 

```php
$send = mail($email->to, str::utf8($email->subject), str::utf8($email->body), implode(PHP_EOL, $headers), "-f info@mydomain.de"); 
```

to get it work.

**Comment by lukasbestle** [comment]
Can't you use the `from` param for the `Email` class with a valid email address?

**Comment by svnt** [comment]
How? Don't know and can't test. Don't use this hoster anymore, sorry.

**Comment by lukasbestle** [comment]
That depends on how you used the Kirby `Email` class. But generally you can set the option in the same array as the `to` address or the `subject`.

Since you can't test it anymore, I'm closing this issue. If someone else has the same issue and can't solve it using a valid `from` address, please open a new issue.
