### ISSUE TITLE
No `something IS NULL` for SQL?

### ISSUE THREAD

**Issue by zx1986** [getkirby/toolkit#127]
There is no `something is NULL` condition for SQL, right?

not working with NULL columns :-(
```
    13 $failed_counter = $calloutdata->where('created_at', 'LIKE', "$today%")¬
    14                                ->andWhere('calling_result', '!=', '2')¬
    15                                ->orWhere('calling_result', 'IS', 'NULL')¬
    16                                ->count();¬
```

**Comment by lukasbestle** [comment]
I think it should work with a real `null` value:

```php
    $failed_counter = $calloutdata->where('created_at', 'LIKE', "$today%")
                                   ->andWhere('calling_result', '!=', '2')
                                   ->orWhere('calling_result', 'IS', null)
                                   ->count();
```

**Comment by zx1986** [comment]
@lukasbestle I had tried that, not work either :-(

**Comment by lukasbestle** [comment]
The database classes have been refactored in the Kirby 2.3 beta 2. `null` as value should indeed work and should have worked previously.

After reading through your code again, I don't really understand what you are trying to do. Couldn't you even remove the line where you are checking for `null` since it is always not equal to 2 anyway?

I'm closing this. Please reopen if you still have this issue and it is related to Kirby. Thanks.
