### ISSUE TITLE
Mailto link does not work - E-Mail Addresses are double obfuscated 

### ISSUE THREAD

**Issue by texnixe** [getkirby/toolkit#200]
https://forum.getkirby.com/t/kirby-2-4-0-are-e-mail-addresses-double-obfuscated/5727

**Comment by lukasbestle** [comment]
I found the issue: The [`htmlspecialchars()` in this line](https://github.com/getkirby/toolkit/blob/master/lib/html.php#L195) is responsible for it.

Looks like the same change is also the reason for [other issues](https://github.com/getkirby/toolkit/commit/2880806fc1da703dce10b47a45d60e5542929e22). Because the change itself is useful, I don't think simply reverting would help. @bastianallgeier?

**Comment by bastianallgeier** [comment]
@lukasbestle I agree! It's simply more secure that way. I think I already fixed all the field issues and I just introduced a new way of defining unescaped attributes to also fix this issue. I think it's more reasonable to give this option, but still keep the default more secure.
