### ISSUE TITLE
a::missing returns true for '0'

### ISSUE THREAD

**Issue by mzur** [getkirby/toolkit#47]
Take this code for example:
```php
$data = array('errors' => '0');
$required = array('errors');
$missing = a::missing($data, $required);
// $missing = array('errors')
```
So the function will report `'errors'` as missing although it is there and contains a value.

This is because of `empty('0')` returning `true`. In my opinion a [check like this](http://stackoverflow.com/a/733175/1796523) should be performed and would always result in the correct behavior.

What do you think? I'd be happy to create a pull request.

**Comment by lukasbestle** [comment]
I would simply replace `empty($array[$r])` with `!array_key_exists($r, $array)`. This should reliably check if the array contains the required keys.

I don't really know if the method is really meant to check for empty values or just for nonexistent values, so it depends on that if this change is useful. Otherwise, your idea is great, but I would also count the number `0` in, not just the string `"0"`. Also, make sure to check for key existence beforehand, otherwise PHP will throw notices all over the place.

**Comment by mzur** [comment]
> I don't really know if the method is really meant to check for empty values or just for nonexistent values

Well, that's the question that needs to be answered first ;-)
Anyway, I for one always used it to check for empty and not for nonexistent values.
